### ISSUE TITLE
Any way of changing file creation date?

### ISSUE THREAD

**Issue by ferfebles** [djberg96/win32-file#4]
I'm trying to solve a problem created by the windows file system tunneling (http://blogs.msdn.com/b/oldnewthing/archive/2005/07/15/439261.aspx) when deleting and creating a file.

By now I only found two solutions: sleep more than 15 seconds between deletion and creation of a new file, or use PowerShell to change the cdate of the file after being created.

I would like to find a way to change the creation date (birth date in Windows) of a file using only Ruby, but I didn't found a way to do it.

There is any way of doing it?

**Comment by djberg96** [comment]
Does SetFileTime work? I haven't tried it. I could add atime=, ctime= and mtime= methods to File::Stat (in win32-file-stat) if it does.

**Comment by ferfebles** [comment]
It works!, with your clue about SetFileTime I found at least two gems that
use the call to change the ctime of a file:
* This one that sounded good, but that didn't work using Time.now as ctime:
https://github.com/windwiny/win32_filetime
* And this one that I adapted and tested successfully:
https://www.omniref.com/ruby/gems/logtwuncator/0.1.6/symbols/LogTwuncator::Win32File::SetFileTime

If you have the time to add this functionality, I will use your gem. I
prefer code that is broadly used and evolves that a little snippet of code
that is tested only in my environment.

By the way, thanks for all your great gems.

This is the code that I tested with this
call Win32File.set_file_time('c:\zz.txt', Time.now) :

require 'Win32API'
# This code has adapted from pdumpfs project
http://raa.ruby-lang.org/project/pdumpfs/
# Uses the Win32API to do win32 system calls to change file dates
module Win32File
  GENERIC_WRITE    = 0x40000000
  GENERIC_EXECUTE  = 0x20000000
  GENERIC_ALL      = 0x10000000
  FILE_SHARE_WRITE = 2
  OPEN_EXISTING    = 3
  GetLocaltime = Win32API.new("kernel32", "GetLocalTime", "P", 'V')
  SystemTimeToFileTime = Win32API.new("kernel32", "SystemTimeToFileTime",
"PP", 'I')
  CreateFile  = Win32API.new("kernel32", "CreateFileA", "PLLLLLL", "L")
  SetFileTime = Win32API.new("kernel32", "SetFileTime", "LPPP", "I")
  CloseHandle = Win32API.new("kernel32", "CloseHandle", "L", "I")
  # Convert Ruby time into win32 FileTime
  def self.get_file_time(time)
    pSYSTEMTIME = ' ' * 2 * 8 # 2byte x 8
    pFILETIME   = ' ' * 2 * 8 # 2byte x 8
    GetLocaltime.call(pSYSTEMTIME)
    time_arr = pSYSTEMTIME.unpack("S8")
    time_arr[0..1] = time.year, time.month
    time_arr[3..6] = time.day, time.hour, time.min, time.sec
    SystemTimeToFileTime.call(time_arr.pack("S8"), pFILETIME)
    pFILETIME
  end
  # Set created, accessed and modified dates for a file
  def self.set_file_time(file, ctime=nil, atime=nil, mtime=nil)
    hFile = 0
    times = [ctime, atime, mtime].collect do |time|
      next( 0 ) if time.nil?
      get_file_time(time.dup.utc)
    end
    hFile = CreateFile.call(file.dup, GENERIC_WRITE, FILE_SHARE_WRITE, 0,
OPEN_EXISTING, 0, 0)
    res = SetFileTime.call(hFile, times[0], times[1], times[2])
    CloseHandle.call(hFile)
    return res
  end
end

**Comment by djberg96** [comment]
@ferfebles Yep, that works. I think I'll get a new version out this weekend that adds the new methods. I'll do a simultaneous release of win32-file-stat and win32-file so you can alter the time in a couple different ways:

```
File.ctime(path, Time.now)
```
Or:
```
stat = File::Stat.new(path)
stat.ctime = Time.now
```

**Comment by ferfebles** [comment]
That will be great. I can test it on XP, 7, 8.1, 2008 & 2012.

**Comment by djberg96** [comment]
Actually, I'm not going to modify File::Stat. I decided that those should be immutable, and it got confusing.

However, I will modify File.atime, File.ctime and File.mtime. I've pushed up an initial implementation. I think there's a potential timezone issue at the moment, so I need to address that first. But, please take a look and see if it's working alright for you.

**Comment by djberg96** [comment]
Alright, now available in win32-file 0.8.0, which I just pushed out. :)

**Comment by ferfebles** [comment]
Thanks!

**Comment by ferfebles** [comment]
I found an error after installing win32-file when requiring win32/file and win32/daemon

```
C:\>irb
DL is deprecated, please use Fiddle
irb(main):001:0> require 'win32/file'
=> true
irb(main):002:0> require 'win32/daemon'
SystemCallError: The data area passed to a system call is too small - GetTokenInformation
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-stat-1.5.2/lib/win32/file/stat.rb:827:in `get_current_process_sid'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-stat-1.5.2/lib/win32/file/stat.rb:81:in `initialize'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file.rb:426:in `new'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/win32-file-0.8.0/lib/win32/file.rb:426:in `file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `block (2 levels) in contains_requirable_file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `each'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `any?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:76:in `block in contains_requirable_file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:74:in `each'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:74:in `any?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb:74:in `contains_requirable_file?'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:943:in `block in find_inactive_by_path'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:942:in `each'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:942:in `find'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:942:in `find_inactive_by_path'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems.rb:185:in `try_activate'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):2
        from C:/Ruby200/bin/irb:12:in `<main>'irb(main):003:0>
```

**Comment by djberg96** [comment]
@ferfebles I will take a look. Please do me a favor and file this as a separate bug.
